---
title: "Unified Seurat"
date: '2024-11-18'
---
```{r}
source("/data/gpfs/projects/punim2183/data_processed/dropEst_analysis_functions.R")
save.image("combined_orig")
```

## Combine Ntrk2 count matrices: 

```{r}

file_paths_orig <- list.files("/data/gpfs/projects/punim2183/count_matrices", full.names = TRUE, pattern = "*_orig*")
count_matrices_orig <- lapply(file_paths_orig, readRDS)
names(count_matrices_orig) <- basename(file_paths_orig)
```

```{r}

count_matrices_extracted_orig <- lapply(count_matrices_orig, function(x) x[["cm"]])

# Get the union of all gene names
all_genes_orig <- Reduce(union, lapply(count_matrices_extracted_orig, rownames))

# Align matrices to have the same rows
aligned_matrices_orig <- lapply(count_matrices_extracted_orig, function(mat) {
  missing_genes <- setdiff(all_genes_orig, rownames(mat)) # Genes not in the matrix
  # Create a sparse matrix for missing genes with zero counts
  missing_mat <- Matrix::sparseMatrix(
    i = integer(0), 
    j = integer(0), 
    dims = c(length(missing_genes), ncol(mat)),
    dimnames = list(missing_genes, colnames(mat))
  )
  # Combine the original matrix with the missing rows
  mat_combined <- rbind(mat, missing_mat)
  # Reorder rows to match all_genes_orig
  mat_combined[match(all_genes_orig, rownames(mat_combined)), , drop = FALSE]
})


# Check if all row names match
#all(sapply(aligned_matrices_orig, rownames) == all_genes_orig)
  
  
combined_matrix_orig <- do.call(cbind, aligned_matrices_orig)

colnames(combined_matrix_orig) <- make.unique(colnames(combined_matrix_orig))

```

## Create a Combined Seurat:

```{r}

combined_seurat_orig <- CreateSeuratObject(
  counts = combined_matrix_orig,  
  min.cells = 3,   # Filter out genes expressed in fewer than 3 cells
  min.features = 200 # Filter out cells expressing fewer than 200 genes
)


# Create a vector indicating the source of each cell
source_ids_orig <- unlist(lapply(names(count_matrices_extracted_orig), function(name) {
  rep(name, ncol(count_matrices_extracted_orig[[name]]))
}))

# Add the source information to the Seurat object
combined_seurat_orig$source <- source_ids_orig

combined_seurat_orig <- preprocess_seurat(combined_seurat_orig)
```


##Ntrk2 Expression
```{r}

Ntrk2_exp <- calc_gene_exp(goi = "Ntrk2", combined_seurat_orig)

FeaturePlot(combined_seurat_orig, features = "Ntrk2")

FeaturePlot(combined_seurat_orig, features = c("Map2", "Rbfox3", "Tubb3", "Mbp", "Olig1", "Olig2", "Gfap", "Aqp4", "Slc1a3"))
```

## cluster cell types based on marker genes: 

```{r}
markers_orig <- find_markers_for_object(combined_seurat_orig)

```