---
title: "merged_seurat"
output: html_document
date: '2024-10-30'
---


Add the sample name in each seurat metadata: 
```{r}
trunc_1$sample <- "10X52_2"
FL_1$sample <- "10X52_2"
both_1$sample <- "10X52_2"
orig_1$sample <- "10X52_2"

trunc_2$sample <- "10X26_3"
FL_2$sample <- "10X26_3"
both_2$sample <- "10X26_3"
orig_2$sample <- "10X26_3"

trunc_3$sample <- "10X26_4"
FL_3$sample <- "10X26_4"
both_3$sample <- "10X26_4"
orig_3$sample <- "10X26_4"


```


combine seurats that have the same isoform representation  
```{r}
combined_orig <- merge(orig_1, y = c(orig_2, orig_3), add.cell.ids = c("10X52_2", "10X26_3", "10X26_4"), project = "Combined_seurat_trunc")

combined_trunc <- merge(trunc_1, y = c(trunc_2, trunc_3), add.cell.ids = c("10X52_2", "10X26_3", "10X26_4"), project = "Combined_seurat_trunc")

combined_FL <- merge(FL_1, y = c(FL_2, FL_3), add.cell.ids = c("10X52_2", "10X26_3", "10X26_4"), project = "Combined_seurat_FL")

combined_both <- merge(both_1, y = c(both_2, both_3), add.cell.ids = c("10X52_2", "10X26_3", "10X26_4"), project = "Combined_seurat_both")


```

then normalise and scale those combined seurats: 

```{r}

# Define a function to standardize the processing pipeline
process_combined <- function(seurat_obj) {
  seurat_obj <- NormalizeData(seurat_obj)
  seurat_obj <- FindVariableFeatures(seurat_obj, selection.method = "vst", nfeatures = 2000)
  seurat_obj <- ScaleData(seurat_obj)
  seurat_obj <- RunPCA(seurat_obj, npcs = 30)
  seurat_obj <- RunUMAP(seurat_obj, dims = 1:20)
  seurat_obj <- FindNeighbors(seurat_obj, dims = 1:20)
  seurat_obj <- FindClusters(seurat_obj, resolution = 0.5)
  
  return(seurat_obj)
}


combined_orig <- process_combined(combined_orig)
combined_trunc <- process_combined(combined_trunc)
combined_FL <- process_combined(combined_FL)
combined_both <- process_combined(combined_both)




```

