---
title: "plots to fix"
output: html_document
date: '2024-06-03'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, fig.height= 8, fig.width= 15}
data <- FetchData(three_samples_seurat, vars = c("Ntrk2", "Class"))

three_samples_df <- data %>% as.data.frame()

vln_3_g <- ggplot(three_samples_df, aes(x = Class, y = Ntrk2, fill = Class)) +
  geom_violin(trim = FALSE) +  # Violin plot
  labs(title = "Ntrk2 Expression within the three-sample subset", 
       x = "Class", 
       y = "Expression Level") +
  theme_minimal() +
  theme(
    axis.text = element_text(size = 28),
    axis.title = element_text(size = 30),
    legend.text = element_text(size = 28),
    legend.title = element_text(size = 30),
    plot.title = element_text(size = 33)
  )

# Print the plot
print(vln_3_g)





# Extract data for three_samples_seurat
data_three <- FetchData(three_samples_seurat, vars = c("Ntrk2", "Class"))
three_samples_df <- data_three %>% as.data.frame()

# Create violin plot for three_samples_seurat
vln_3_g <- ggplot(three_samples_df, aes(x = Class, y = Ntrk2, fill = Class)) +
  geom_violin(trim = FALSE) +  # Violin plot
  geom_jitter(width = 0.2, size = 0.5, alpha = 0.5) +  # Add jittered points for better visualization of individual points
  labs(title = "Ntrk2 Expression within the three-sample subset", 
       x = "Class", 
       y = "Expression Level") +
  theme_minimal() +
  theme(
    axis.text = element_text(size = 28),
    axis.title = element_text(size = 30),
    legend.text = element_text(size = 28),
    legend.title = element_text(size = 30),
    plot.title = element_text(size = 33)
  )

# Print the plot
print(vln_3_g)

# Extract data for eleven_samples_seurat
data_eleven <- FetchData(eleven_samples_seurat, vars = c("Ntrk2", "Class"))
eleven_samples_df <- data_eleven %>% as.data.frame()

# Create violin plot for eleven_samples_seurat
vln_11_g <- ggplot(eleven_samples_df, aes(x = Class, y = Ntrk2, fill = Class)) +
  geom_violin(trim = FALSE) +  # Violin plot
  geom_jitter(width = 0.2, size = 0.5, alpha = 0.5) +  # Add jittered points for better visualization of individual points
  labs(title = "Ntrk2 Expression within the eleven-sample subset", 
       x = "Class", 
       y = "Expression Level") +
  theme_minimal() +
  theme(
    axis.text = element_text(size = 28),
    axis.title = element_text(size = 30),
    legend.text = element_text(size = 28),
    legend.title = element_text(size = 30),
    plot.title = element_text(size = 33)
  )

# Print the plot
print(vln_11_g)

# Extract data for mouse_cortex_data
data_cortex <- FetchData(mouse_cortex_data, vars = c("Ntrk2", "Class"))
mouse_cortex_df <- data_cortex %>% as.data.frame()

# Create violin plot for mouse_cortex_data
vln_cortex_g <- ggplot(mouse_cortex_df, aes(x = Class, y = Ntrk2, fill = Class)) +
  geom_violin(trim = FALSE) +  # Violin plot
  geom_jitter(width = 0.2, size = 0.5, alpha = 0.5) +  # Add jittered points for better visualization of individual points
  labs(title = "Ntrk2 Expression within the mouse cortex dataset", 
       x = "Class", 
       y = "Expression Level") +
  theme_minimal() +
  theme(
    axis.text = element_text(size = 28),
    axis.title = element_text(size = 30),
    legend.text = element_text(size = 28),
    legend.title = element_text(size = 30),
    plot.title = element_text(size = 33)
  )

# Print the plot
print(vln_cortex_g)


mouse_cortex_data_cOi <- subset(mouse_cortex_data, subset = Class %in% cell_types_of_interest)
# Extract data for Ntrk2 expression from the subsetted Seurat object
data_cortex_cOi <- FetchData(mouse_cortex_data_cOi, vars = c("Ntrk2", "Class"))

# Convert to dataframe
mouse_cortex_df_cOi <- data_cortex_cOi %>% as.data.frame()

# Create the violin plot for the subsetted data
vln_cortex_cOi_g <- ggplot(mouse_cortex_df_cOi, aes(x = Class, y = Ntrk2, fill = Class)) +
  geom_violin(trim = FALSE) +  # Violin plot
  geom_jitter(width = 0.2, size = 0.5, alpha = 0.5) +  # Add jittered points for better visualization of individual points
  labs(title = "Ntrk2 Expression by Cell Types of Interest Within the Mouse Cortex Dataset", 
       x = "Class", 
       y = "Expression Level") +
  theme_minimal() +
  theme(
    axis.text = element_text(size = 28),
    axis.title = element_text(size = 30),
    legend.text = element_text(size = 28),
    legend.title = element_text(size = 30),
    plot.title = element_text(size = 33)
  )

# Print the plot
print(vln_cortex_cOi_g)


```
```{r}
# Example R code to visualize distribution and determine thresholds

# Load necessary libraries
library(ggplot2)
library(Seurat)

# Fetch Ntrk2 expression data
expression_data <- FetchData(subset_500, vars = "Ntrk2")

# Convert to dataframe
expression_df <- expression_data %>% as.data.frame()

# Plot the distribution of Ntrk2 expression values
ggplot(expression_df, aes(x = Ntrk2)) +
  geom_histogram(bins = 50, fill = "blue", alpha = 0.7) +
  labs(title = "Distribution of Ntrk2 Expression",
       x = "Log-Transformed Expression Level",
       y = "Frequency") +
  theme_minimal()

# Determine quantiles for thresholds
quantiles <- quantile(expression_df$Ntrk2, probs = c(0.25, 0.75))

# Print quantiles to set thresholds
print(quantiles)



# Extract Ntrk2 expression data
expression_data <- FetchData(s_500_a, vars = c("Ntrk2", "Class"))

# Convert to dataframe
expression_df <- expression_data %>% as.data.frame()

# Plot the distribution of Ntrk2 expression values
ggplot(expression_df, aes(x = Ntrk2)) +
  geom_histogram(bins = 50, fill = "blue", alpha = 0.7) +
  labs(title = "Distribution of Ntrk2 Expression",
       x = "Log-Transformed Expression Level",
       y = "Frequency") +
  theme_minimal()

# Exclude zero expression cells
non_zero_expression_df <- expression_df[expression_df$Ntrk2 > 0, ]

# Calculate quantiles for non-zero expressing cells
quantiles_non_zero <- quantile(non_zero_expression_df$Ntrk2, probs = c(0.25, 0.5, 0.75))

# Print quantiles for non-zero expressing cells
print(quantiles_non_zero)

# Example of setting thresholds based on these quantiles
low_threshold <- quantiles_non_zero[1]  # 25th percentile
high_threshold <- quantiles_non_zero[3]  # 75th percentile

# Subset the cells based on these thresholds
low_expression_cells <- subset(mouse_cortex_data, subset = Ntrk2 > 0 & Ntrk2 <= low_threshold)
high_expression_cells <- subset(mouse_cortex_data, subset = Ntrk2 > high_threshold)

# Print the number of cells in each category
cat("Number of cells with low Ntrk2 expression:", nrow(low_expression_cells), "\n")
cat("Number of cells with high Ntrk2 expression:", nrow(high_expression_cells), "\n")


```

```{r}
plot_cell_type_counts <- function(counts_df, df_name) {
  title_text <- sprintf("Cell Type Counts per Sample\n(Data Frame: %s)", df_name)

  ggplot(counts_df, aes(x = counts_df, y = Count, fill = CellType)) +
    geom_bar(stat = "identity", position = "dodge") +
    labs(title = title_text,
         x = "Sample",
         y = "Cell Count",
         fill = "Cell Type") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 60, hjust = 1))
}


```


```{r}
correct_column_names <- c("Sample", "Count", "CellType")

colnames(min_500) <- correct_column_names
colnames(min_750) <- correct_column_names
colnames(min_1000) <- correct_column_names
colnames(min_1200) <- correct_column_names


```
```{r}
min_500 <- data.frame(
  Sample = min_500[,1],
  Astrocytes = min_500[1, "Astrocytes"],
  Neurons = min_500[1, "Neurons"],
  Oligos = min_500[1, "Oligos"]
)
min_500$Sample
min_500
```


```{r}
plot_cell_type_counts <- function(counts_df, df_name) {
  title_text <- sprintf("Cell Type Counts per Sample\n(Data Frame: %s)", df_name)

  ggplot(counts_df, aes(x = Sample, y = Count, fill = CellType)) +
    geom_bar(stat = "identity", position = "dodge") +
    labs(title = title_text,
         x = "Sample",
         y = "Cell Count",
         fill = "Cell Type") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 60, hjust = 1))
}


p_500 <- plot_cell_type_counts(min_500, "minimum 500")
p_750 <- plot_cell_type_counts(min_750, "minimum 750")
p_1000 <- plot_cell_type_counts(min_1000, "minimum 1000")
p_1200 <- plot_cell_type_counts(min_1200, "minimum 1200")

p_500
p_750
p_1000
p_1200


```
```{r}

# Function to convert rownames to column and reshape the data
prepare_data <- function(df, min_count) {
  df <- as.data.frame(df)
  df$Sample <- rownames(df)
  df_long <- df %>%
    pivot_longer(cols = -Sample, names_to = "CellType", values_to = "Count")
  return(df_long)
}

# Applying the function to each filtered data frame
min_500 <- filter_samples_by_min_count(mouse_cortex_data, 500)
min_500_long <- prepare_data(min_500, 500)

min_750 <- filter_samples_by_min_count(mouse_cortex_data, 750)
min_750_long <- prepare_data(min_750, 750)

min_1000 <- filter_samples_by_min_count(mouse_cortex_data, 1000)
min_1000_long <- prepare_data(min_1000, 1000)

min_1200 <- filter_samples_by_min_count(mouse_cortex_data, 1200)
min_1200_long <- prepare_data(min_1200, 1200)

# Bind all data frames into one
combined_df <- bind_rows(
  min_500_long %>% mutate(Threshold = "500"),
  min_750_long %>% mutate(Threshold = "750"),
  min_1000_long %>% mutate(Threshold = "1000"),
  min_1200_long %>% mutate(Threshold = "1200")
)

# Define the plotting function
plot_cell_type_counts <- function(counts_df, df_name) {
  title_text <- sprintf("Cell Type Counts per Sample\n(Data Frame: %s)", df_name)

  ggplot(counts_df, aes(x = Sample, y = Count, fill = CellType)) +
    geom_bar(stat = "identity", position = "dodge") +
    labs(title = title_text,
         x = "Sample",
         y = "Cell Count",
         fill = "Cell Type") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 60, hjust = 1))
}



```

```{r plot_chunck, fig.width=12, fig.height=6}

# Add a new column 'Threshold' to each dataframe
min_500$Threshold <- "500"
min_750$Threshold <- "750"
min_1000$Threshold <- "1000"
min_1200$Threshold <- "1200"


# Combine the dataframes
combined_df_1<- rbind(min_500, min_750)
combined_df_1$Threshold <- factor(combined_df_1$Threshold)
combined_df_1 <- combined_df_1 %>%
  mutate(Threshold = factor(Threshold, levels = c(500, 750)))

combined_df_2 <- rbind(min_1000, min_1200)
combined_df_2$Threshold <- factor(combined_df_2$Threshold)
combined_df_2 <- combined_df_2 %>%
  mutate(Threshold = factor(Threshold, levels = c(1000, 1200)))

combined_df <- combined_df %>%
  mutate(Threshold = factor(Threshold, levels = c(500, 750, 1000, 1200)))

plot_1 <- ggplot(combined_df_1, aes(x = Sample, y = Count)) +
  geom_boxplot(aes(fill = as.factor(Threshold))) +
  facet_wrap(~ Threshold, scales = "free_y") +
  labs(title = "Cell Counts by Threshold Across Samples",
       x = "Sample",
       y = "Cell Count",
       fill = "Threshold") +
  theme_minimal() +
        theme( axis.text.x = element_text(angle = 45, hjust = 1, size = 12),
         axis.title.x = element_text(size = 18),
         axis.text.y = element_text(size = 15),  
         axis.title.y = element_text(size = 18),  
         plot.title = element_text(size = 18),
         legend.text = element_text(size = 18),
         legend.title = element_text(size = 18)
  )


colors <- c("1000" = "#C77CFF", "1200" = "#6FB07F")
plot_2 <- ggplot(combined_df_2, aes(x = Sample, y = Count)) +
  geom_boxplot(aes(fill = as.factor(Threshold))) +
  facet_wrap(~ Threshold, scales = "free_y") +
  labs(title = "Cell Counts by Threshold Across Samples",
       x = "Sample",
       y = "Cell Count",
       fill = "Threshold") +
    scale_fill_manual(values = colors) + 
  theme_minimal() +
    theme_minimal() +
        theme( axis.text.x = element_text(angle = 45, hjust = 1, size = 12),
         axis.title.x = element_text(size = 18),
         axis.text.y = element_text(size = 15),  
         axis.title.y = element_text(size = 18),  
         plot.title = element_text(size = 18),
         legend.text = element_text(size = 18),
         legend.title = element_text(size = 18)
  )

print(plot_1)
print(plot_2)
```
```{r}


```

```{r}
# Exclude zero expression cells
non_zero_expression_df <- expression_df[expression_df$Ntrk2 > 0, ]

# Calculate quantiles for non-zero expressing cells
quantiles_non_zero <- quantile(non_zero_expression_df$Ntrk2, probs = c(0.25, 0.5, 0.6))

# Print quantiles for non-zero expressing cells
print(quantiles_non_zero)

# Set adjusted thresholds
low_threshold <- quantiles_non_zero[1]  # 25th percentile
moderate_threshold <- quantiles_non_zero[2]  # 50th percentile
adjusted_high_threshold <- quantiles_non_zero[2]  # 50th percentile

# Filtering samples function adjusted with new threshold
filter_samples_by_gene_expression_O <- function(seurat_object, gene, threshold, percentage_threshold, cell_types_of_interest) {
  samples_to_keep <- list()
  sample_ids <- unique(seurat_object$SampleID)
  seurat_object$SampleID <- as.character(seurat_object$SampleID)
  
  for (sample_id in sample_ids) {
    results_per_cell_type <- list()
    all_cell_types_met <- TRUE
    
    for (cell_type in cell_types_of_interest) {
      subset_cells <- subset(seurat_object, subset = SampleID == sample_id & Class == cell_type)
      expression_data <- FetchData(subset_cells, vars = gene)
      
      if (nrow(expression_data) > 0) {  # Ensure there are cells to avoid division by zero
        proportion_above_threshold <- sum(expression_data[, gene] > threshold, na.rm = TRUE) / nrow(expression_data) * 100
        
        if (proportion_above_threshold >= percentage_threshold) {
          results_per_cell_type[[cell_type]] <- list(
            proportion_above_threshold = proportion_above_threshold,
            num_cells = nrow(expression_data)
          )
        } else {
          all_cell_types_met <- FALSE
          break
        }
      } else {
        message(paste("No cells found for SampleID:", sample_id, "and Class:", cell_type))
        all_cell_types_met <- FALSE
        break
      }
    }
    
    if (all_cell_types_met) {
      samples_to_keep[[sample_id]] <- results_per_cell_type
    }
  }
  
  if (length(samples_to_keep) == 0) {
    print("No samples met the threshold criteria.")
  } else {
    print(paste("Samples meeting criteria:", length(samples_to_keep)))
  }
  
  for (sample_id in names(samples_to_keep)) {
    cat(paste("Sample ID:", sample_id, "\n"))
    for (cell_type in names(samples_to_keep[[sample_id]])) {
      cat(paste("  Cell Type:", cell_type, 
                "- Proportion Above Threshold:", samples_to_keep[[sample_id]][[cell_type]]$proportion_above_threshold,
                "- Number of Cells:", samples_to_keep[[sample_id]][[cell_type]]$num_cells, "\n"))
    }
  }
  
  return(names(samples_to_keep))
}

# Define the parameters
gene <- "Ntrk2"
threshold <- 1  
threshold_2 <- 0.1
percentage_threshold <- 5 
percentage_threshold_2 <- 10
percentage_threshold_3 <- 20
percentage_threshold_4 <- 15
cell_types_of_interest <- c("Astrocytes", "Neurons", "Oligos")

# Filter samples with adjusted high threshold
by_gene_adjusted_500 <- filter_samples_by_gene_expression_O(subset_500, gene, threshold, percentage_threshold, cell_types_of_interest)
by_gene_adjusted_750 <- filter_samples_by_gene_expression_O(subset_750, gene, threshold, percentage_threshold, cell_types_of_interest)
by_gene_adjusted_1000 <- filter_samples_by_gene_expression_O(subset_1000, gene, threshold, percentage_threshold, cell_types_of_interest)
by_gene_adjusted_1200 <- filter_samples_by_gene_expression_O(subset_1200, gene, threshold, percentage_threshold, cell_types_of_interest)


by_gene_adjusted_500 <- filter_samples_by_gene_expression_O(subset_500, gene, threshold, percentage_threshold_2, cell_types_of_interest)
by_gene_adjusted_750 <- filter_samples_by_gene_expression_O(subset_750, gene, threshold, percentage_threshold_2, cell_types_of_interest)
by_gene_adjusted_1000 <- filter_samples_by_gene_expression_O(subset_1000, gene, threshold, percentage_threshold_2, cell_types_of_interest)
by_gene_adjusted_1200 <- filter_samples_by_gene_expression_O(subset_1200, gene, threshold, percentage_threshold_2, cell_types_of_interest)

by_gene_adjusted_500 <- filter_samples_by_gene_expression_O(subset_500, gene, threshold, percentage_threshold_3, cell_types_of_interest)
by_gene_adjusted_750 <- filter_samples_by_gene_expression_O(subset_750, gene, threshold, percentage_threshold_3, cell_types_of_interest)
by_gene_adjusted_1000 <- filter_samples_by_gene_expression_O(subset_1000, gene, threshold, percentage_threshold_3, cell_types_of_interest)
by_gene_adjusted_1200 <- filter_samples_by_gene_expression_O(subset_1200, gene, threshold, percentage_threshold_3, cell_types_of_interest)


by_gene_adjusted_500 <- filter_samples_by_gene_expression_O(subset_500, gene, threshold, percentage_threshold_4, cell_types_of_interest)
by_gene_adjusted_750 <- filter_samples_by_gene_expression_O(subset_750, gene, threshold, percentage_threshold_4, cell_types_of_interest)
by_gene_adjusted_1000 <- filter_samples_by_gene_expression_O(subset_1000, gene, threshold, percentage_threshold_4, cell_types_of_interest)
by_gene_adjusted_1200 <- filter_samples_by_gene_expression_O(subset_1200, gene, threshold, percentage_threshold_4, cell_types_of_interest)




by_gene_adjusted_500 <- filter_samples_by_gene_expression_O(subset_500, gene, threshold_2, percentage_threshold, cell_types_of_interest)
by_gene_adjusted_750 <- filter_samples_by_gene_expression_O(subset_750, gene, threshold_2, percentage_threshold, cell_types_of_interest)
by_gene_adjusted_1000 <- filter_samples_by_gene_expression_O(subset_1000, gene, threshold_2, percentage_threshold, cell_types_of_interest)
by_gene_adjusted_1200 <- filter_samples_by_gene_expression_O(subset_1200, gene, threshold_2, percentage_threshold, cell_types_of_interest)

by_gene_adjusted_500 <- filter_samples_by_gene_expression_O(subset_500, gene, threshold_2, percentage_threshold_2, cell_types_of_interest)
by_gene_adjusted_750 <- filter_samples_by_gene_expression_O(subset_750, gene, threshold_2, percentage_threshold_2, cell_types_of_interest)
by_gene_adjusted_1000 <- filter_samples_by_gene_expression_O(subset_1000, gene, threshold_2, percentage_threshold_2, cell_types_of_interest)
by_gene_adjusted_1200 <- filter_samples_by_gene_expression_O(subset_1200, gene, threshold_2, percentage_threshold_2, cell_types_of_interest)

by_gene_adjusted_500 <- filter_samples_by_gene_expression_O(subset_500, gene, threshold_2, percentage_threshold_3, cell_types_of_interest)
by_gene_adjusted_750 <- filter_samples_by_gene_expression_O(subset_750, gene, threshold_2, percentage_threshold_3, cell_types_of_interest)
by_gene_adjusted_1000 <- filter_samples_by_gene_expression_O(subset_1000, gene, threshold_2, percentage_threshold_3, cell_types_of_interest)
by_gene_adjusted_1200 <- filter_samples_by_gene_expression_O(subset_1200, gene, threshold_2, percentage_threshold_3, cell_types_of_interest)


by_gene_adjusted_500 <- filter_samples_by_gene_expression_O(subset_500, gene, threshold_2, percentage_threshold_4, cell_types_of_interest)
by_gene_adjusted_750 <- filter_samples_by_gene_expression_O(subset_750, gene, threshold_2, percentage_threshold_4, cell_types_of_interest)
by_gene_adjusted_1000 <- filter_samples_by_gene_expression_O(subset_1000, gene, threshold_2, percentage_threshold_4, cell_types_of_interest)
by_gene_adjusted_1200 <- filter_samples_by_gene_expression_O(subset_1200, gene, threshold_2, percentage_threshold_4, cell_types_of_interest)

```
