#!/bin/bash
#SBATCH --job-name=dropest_job_2         # Job name
#SBATCH --output=dropest_output.txt    # Standard output and error log
#SBATCH --error=dropest_error.txt      # Error log
#SBATCH --nodes=4                     # Number of nodes
#SBATCH --ntasks-per-node=1            # Number of tasks (processes) per node
#SBATCH --cpus-per-task=8              # Number of CPU cores per task
#SBATCH --mem=50G                     # Memory per node
#SBATCH --time=1:00:00                # Time limit hrs:min:sec
#SBATCH --partition=bigmem            # Partition name (if needed)



module load foss/2022a
module load dropEst/0.8.6
module load unimelb-mf-clients

dropest -f -g ./gencode.vM10.orig_s.gtf -L e -c ./config.xml ./10X26_4.bam.1
